### ISSUE TITLE
Unnecessary vibra enabled for minimal notification

### ISSUE THREAD

**Issue by vitalyster** [streaka/node-pushnotifications-http2#2]
Minimal notification with just a title and body appears silently on screen in node-pushnotifications, while it vibrates in note-pushnotifications-http2

**Comment by jpike88** [comment]
try with latest master and tell me if it persists, I've updated the dependency

**Comment by vitalyster** [comment]
When I try to add package from master it tries to run its tests and tests are failed

**Comment by jpike88** [comment]
Tests probably do fail, because I tweaked it in my fork to use http2. Closing
