### ISSUE TITLE
Unable to send notification

### ISSUE THREAD

**Issue by samsprakash** [streaka/node-pushnotifications-http2#5]
I am using AWS lambda, API gateway and node version 8.10.  unable to send push notification, I am getting timeout error.  API Gateway requests will timeout after 30 sec.  I checked the same code in my local machine, it is working fine. I am not sure why I am getting error in AWS lambda.

**Comment by jpike88** [comment]
Me neither, works fine on ec2/elastic beanstalk etc... likely due to incorrect port configuration/blockage?

**Comment by samsprakash** [comment]
Port and configurations are fine. When I call the push.send(ids,data), I didn't get any response. Is it because of memory leak? Or taking longer to execute the function?

**Comment by jpike88** [comment]
Profile a lambda call. What happens to memory usage etc? Most of this is hard to diagnose without more context.

I doubt it's a memory leak if the lambda call isn't doing an insane amount of pushes. A memory leak wouldn't result in non functionality, this library really isn't that memory intensive. Stick some console logs deep in the library as a last resort.

**Comment by samsprakash** [comment]
@jpike88 :Thanks for your quick response. issue is my lambda functions doesn't have external internet access in AWS. I fixed  this issue. It's working like a charm.
